on:
  workflow_dispatch:
jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'gluonhq/gluon-samples'
          ref: '6988d463f260be783b2e6cb614414a333c8a977b'
          fetch-depth: 0
      - uses: gluonhq/setup-graalvm@master
        with:
          graalvm: '22.1.0.1-Final'
          jdk: 'java17'
          arch: aarch64
          #arch: x86_64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - working-directory: ./HelloGluon
        run: |
          java -version
          javac -version
          grep -R --line-number -E "21|--release|maven.compiler.release|maven.compiler.source|maven.compiler.target|sourceCompatibility|targetCompatibility|languageVersion|release" || true
          mvn -N io.takari:maven:wrapper -Dmaven=3.8.8
          ./mvnw -v
          ./mvnw -Pios gluonfx:build
