on:
  workflow_dispatch:
jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'gluonhq/gluon-samples'
      - uses: gluonhq/setup-graalvm@master
        with:
          graalvm: '22.1.0.1-Final'
          jdk: 'java17'
          arch: aarch64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - working-directory: ./HelloGluon
        run: mvn -Pios gluonfx:build
