on:
  workflow_dispatch:
jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'gluonhq/gluon-samples'
      - uses: gluonhq/setup-graalvm@master
        with:
          graalvm: '23+25.1-dev-2409082136'
          jdk: 'java23'
          arch: aarch64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - working-directory: ./HelloGluon
        run: |
          java -version
          javac -version
          grep -R --line-number -E "21|--release|maven.compiler.release|maven.compiler.source|maven.compiler.target|sourceCompatibility|targetCompatibility|languageVersion|release" || true
          mvn -Pios gluonfx:build
